# Generated by Django 4.0.3 on 2022-03-25 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите марку автомобиля', max_length=50, verbose_name='Марка автомобиля')),
                ('model', models.CharField(help_text='Введите модель автомобиля', max_length=50, verbose_name='Модель автомобиля')),
                ('reg_number', models.CharField(help_text='Введите рег.номер автомобиля', max_length=20, verbose_name='Рег.номер автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите категорию автомобиля', max_length=200, verbose_name='Категория автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите состояние автомобиля', max_length=50, verbose_name='Состояние автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите страну производителя', max_length=50, verbose_name='Страна производителя')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите статус автомобиля', max_length=20, verbose_name='Статус автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='CarInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_num', models.CharField(help_text='Введите номер автомобиля в автопарке', max_length=20, verbose_name='Номер автомобиля в парке')),
                ('date_start', models.DateField(blank=True, help_text='Введите начало срока аренды', null=True, verbose_name='Дата начала статуса')),
                ('date_back', models.DateField(blank=True, help_text='Введите конец срока аренды', null=True, verbose_name='Дата окончания статуса')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.car')),
                ('status', models.ForeignKey(help_text='Изменить статус автомобиля', on_delete=django.db.models.deletion.CASCADE, to='catalog.status', verbose_name='Статус автомобиля')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(help_text='Выберите категорию автомобиля', on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='condition',
            field=models.ForeignKey(help_text='Выберите состояние автомобиля', on_delete=django.db.models.deletion.CASCADE, to='catalog.condition', verbose_name='Состояние автомобиля'),
        ),
        migrations.AddField(
            model_name='car',
            name='country',
            field=models.ForeignKey(help_text='Выберите страну производства', on_delete=django.db.models.deletion.CASCADE, to='catalog.country', verbose_name='Страна производства'),
        ),
    ]
