# Generated by Django 4.0.3 on 2022-03-29 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_carinstance_inv_num_car_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['num']},
        ),
        migrations.AlterModelOptions(
            name='carinstance',
            options={'ordering': ['date_back']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'country'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'statuses'},
        ),
        migrations.AlterField(
            model_name='carinstance',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.car', verbose_name='Автомобиль'),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Введите имя клиента', max_length=30, verbose_name='Имя клиента')),
                ('last_name', models.CharField(help_text='Введите фамилию клиента', max_length=30, verbose_name='Фамилия клиента')),
                ('car_reserv', models.ForeignKey(help_text='Забронированный автомобиль', on_delete=django.db.models.deletion.CASCADE, to='catalog.carinstance', verbose_name='Выберите втомобиль')),
            ],
        ),
    ]
