# Generated by Django 4.0.3 on 2022-03-29 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_car_options_alter_carinstance_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='car_reserv',
        ),
        migrations.AddField(
            model_name='carinstance',
            name='client',
            field=models.ForeignKey(help_text='Выберите клиента', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.client', verbose_name='Клиент'),
        ),
    ]
